[package]
name = "video_view_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.82.0" 
anyhow = "1.0"
clang-sys = "1.6.1"
commands = "0.0.5"